### ISSUE TITLE
input problem, what is correct format?

### ISSUE THREAD

**Issue by DPijnenburg** [tercen/ETS_app#2]
The ETS App Input file from us does not work.
From BioNavigator we had exported  2 Flatfiles of Median Signal m Bkg and signal saturation.
Then we imported these files into Tercen.
In the step prior to the ETS App step (Data input) we selected both these files together.
In the Wizard steps, where we indicate Median Signal input, there are no data points, and we cannot proceed with App.
We dont understand what is wrong in our input files.
https://tercen.com/PamgeneEvaluators/w/55e571dbb0116a6e3bea822d70e537c7

**Comment by ginberg** [comment]
hi @DPijnenburg, your input files are not wrong. The problem is that the filter in the last step of the wizard can't handle that the signal saturation is not in both data files. If you remove the filter and press Apply filter, the data should appear in the view.

If you join the input files, building the view in the app does work. I have added that situation in the same workflow
https://tercen.com/PamgeneEvaluators/w/55e571dbb0116a6e3bea822d70e537c7
please let me know if this is working for you
